version: '3'

services:
  publify-api:
    build: .
    image: manuossz/tcc-gemini-api
    container_name: publify-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    # volumes:
    #   - .:/app
    env_file:
      - .env
